### PR TITLE
Fix infinite loop in ancestor traversal

### LINKED ISSUE #1: Infinite loop when traversing multiple-leveled spans
Example:
```rust
use tracing::{info, info_span};

fn main() {
    use tracing_subscriber::layer::SubscriberExt;

    let layer = tracing_fluentd::Builder::new("rust")
        .flatten()
        .layer()
        .expect("Create layer");
    let sub = tracing_subscriber::Registry::default().with(layer);
    let _guard = tracing::subscriber::set_default(sub);

    info_span!("outer").in_scope(|| {
        info_span!("inner").in_scope(|| {
            info!("Info!");
        });
    });
}
```

When running this program with `cargo run`, it never exits, but instead gets stuck in an infinite loop trying to traverse all the parents of the span.

### PR DESCRIPTION
**Pull request by yotamofek**
First of all, just want to say thank you for this crate! :)

Previously, this line would loop infinitely, since it was always retrieving the leaf span's parent, instead of the current span's parent:
```rust
while let Some(span) = span.parent() {
```
This PR uses [`SpanRef::scope`](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/registry/struct.SpanRef.html#method.scope) to properly traverse the parents of the span being recorded.

Fixes #1

### CODE REVIEW

File: src/tracing.rs [hunk 1]
```diff
@@ -97,14 +94,10 @@ impl FieldFormatter for FlattenFmt {
         event.record(event_record.deref_mut());
 
         if let Some(span) = current_span {
-            let extensions = span.extensions();
-            if let Some(record) = extensions.get::<fluent::Map>() {
-                event_record.update(record);
-            }
-            while let Some(span) = span.parent() {
+            for span in span.scope() {
```
Comment (DoumanAsh) [inline src/tracing.rs:97]: Does it traverse current and all parents?

Comment (DoumanAsh) [reply src/tracing.rs:97]: I don't really get why it behaves differently from `scope` but since `tracing` is poorely documented I need to check their code

**Review by DoumanAsh — APPROVED** [review]

File: src/tracing.rs [hunk 2]
```diff
@@ -64,10 +64,7 @@ impl FieldFormatter for NestedFmt {
 
         if let Some(span) = current_span {
             let extensions = span.extensions();
-            if let Some(record) = extensions.get::<fluent::Map>() {
-                event_record.insert(span.name().to_owned(), record.clone().into());
-            }
-            while let Some(span) = span.parent() {
+            for span in span.scope() {
```
Comment (DoumanAsh) [inline src/tracing.rs:67]: does `scope` include `current_span`?

**Review by DoumanAsh — APPROVED** [review]

**Comment by DoumanAsh** [comment]
I made small update https://github.com/DoumanAsh/tracing-fluentd/commit/ca57edd1267a49410c0e003f5c467c445f9463f3 and will release it soon
